insert into store_catalog (id, name, kind, color, ink, glyph, sort_order, custom) values
  ('spotify', 'Spotify', 'store', '#1DB954', 'light', 'wave', 1, false),
  ('apple-music', 'Apple Music', 'store', '#FC3C44', 'light', 'note', 2, false),
  ('youtube-music', 'YouTube Music', 'store', '#FF0033', 'light', 'play', 3, false),
  ('amazon-music', 'Amazon Music', 'store', '#25D1DA', 'dark', 'disc', 4, false),
  ('deezer', 'Deezer', 'store', '#A238FF', 'light', 'hex', 5, false),
  ('tidal', 'TIDAL', 'store', '#111111', 'light', 'wave', 6, false),
  ('soundcloud', 'SoundCloud', 'store', '#FF5500', 'light', 'cloud', 7, false),
  ('bandcamp', 'Bandcamp', 'store', '#1DA0C3', 'light', 'cassette', 8, false),
  ('audiomack', 'Audiomack', 'store', '#FFA200', 'dark', 'headphones', 9, false),
  ('boomplay', 'Boomplay', 'store', '#E1251B', 'light', 'bolt', 10, false),
  ('anghami', 'Anghami', 'store', '#7A1FA2', 'light', 'note', 11, false),
  ('jiosaavn', 'JioSaavn', 'store', '#1ECCB0', 'dark', 'play', 12, false),
  ('gaana', 'Gaana', 'store', '#E31E25', 'light', 'radio', 13, false),
  ('wynk', 'Wynk Music', 'store', '#C8102E', 'light', 'mic', 14, false),
  ('napster', 'Napster', 'store', '#1A1A1A', 'light', 'disc', 15, false),
  ('pandora', 'Pandora', 'store', '#3668FF', 'light', 'heart', 16, false),
  ('iheartradio', 'iHeartRadio', 'store', '#C6002B', 'light', 'heart', 17, false),
  ('qobuz', 'Qobuz', 'store', '#2B2B2B', 'light', 'diamond', 18, false),
  ('beatport', 'Beatport', 'store', '#94D500', 'dark', 'pulse', 19, false),
  ('traxsource', 'Traxsource', 'store', '#111111', 'light', 'rings', 20, false),
  ('juno', 'Juno Download', 'store', '#F15A24', 'light', 'disc', 21, false),
  ('7digital', '7digital', 'store', '#222222', 'light', 'hex', 22, false),
  ('tiktok', 'TikTok', 'store', '#111111', 'light', 'note', 23, false),
  ('shazam', 'Shazam', 'store', '#0088FF', 'light', 'star', 24, false),
  ('genius', 'Genius', 'store', '#F5E64A', 'dark', 'mic', 25, false),
  ('musixmatch', 'Musixmatch', 'store', '#FF6050', 'light', 'note', 26, false),
  ('discogs', 'Discogs', 'store', '#333333', 'light', 'disc', 27, false),
  ('beatstars', 'BeatStars', 'store', '#FF3B30', 'light', 'star', 28, false),
  ('unitedmasters', 'UnitedMasters', 'store', '#111111', 'light', 'diamond', 29, false),
  ('songkick', 'Songkick', 'store', '#F80046', 'light', 'radio', 30, false),
  ('bandsintown', 'Bandsintown', 'store', '#00B3A4', 'dark', 'mic', 31, false),
  ('ra', 'Resident Advisor', 'store', '#000000', 'light', 'hex', 32, false),
  ('mixcloud', 'Mixcloud', 'store', '#5000FF', 'light', 'cloud', 33, false),
  ('hearthis', 'HearThis.at', 'store', '#222222', 'light', 'headphones', 34, false),
  ('kkbox', 'KKBOX', 'store', '#00A0E9', 'light', 'play', 35, false),
  ('netease', 'NetEase Cloud Music', 'store', '#E60026', 'light', 'cloud', 36, false),
  ('joox', 'JOOX', 'store', '#09D3AC', 'dark', 'bolt', 37, false),
  ('melon', 'Melon', 'store', '#00CD3C', 'dark', 'disc', 38, false),
  ('line-music', 'LINE MUSIC', 'store', '#00B900', 'light', 'note', 39, false),
  ('yandex-music', 'Yandex Music', 'store', '#FFCC00', 'dark', 'play', 40, false),
  ('claro', 'Claro música', 'store', '#DA291C', 'light', 'radio', 41, false),
  ('hungama', 'Hungama', 'store', '#5B2C83', 'light', 'headphones', 42, false),
  ('trebel', 'Trebel', 'store', '#6C2BD9', 'light', 'wave', 43, false),
  ('boomkat', 'Boomkat', 'store', '#111111', 'light', 'cassette', 44, false),
  ('bandlab', 'BandLab', 'store', '#E31C3D', 'light', 'mic', 45, false),
  ('datpiff', 'DatPiff', 'store', '#1C1C1C', 'light', 'cloud', 46, false),
  ('spinrilla', 'Spinrilla', 'store', '#111111', 'light', 'rings', 47, false),
  ('audius', 'Audius', 'store', '#CC0FE0', 'light', 'pulse', 48, false),
  ('idagio', 'IDAGIO', 'store', '#111111', 'light', 'diamond', 49, false),
  ('pretzel', 'Pretzel', 'store', '#7C3AED', 'light', 'star', 50, false),
  ('instagram', 'Instagram', 'social', '#C13584', 'light', 'rings', 1, false),
  ('social-tiktok', 'TikTok', 'social', '#111111', 'light', 'note', 2, false),
  ('youtube', 'YouTube', 'social', '#FF0033', 'light', 'play', 3, false),
  ('x', 'X', 'social', '#111111', 'light', 'bolt', 4, false),
  ('facebook', 'Facebook', 'social', '#1877F2', 'light', 'rings', 5, false),
  ('threads', 'Threads', 'social', '#111111', 'light', 'rings', 6, false),
  ('snapchat', 'Snapchat', 'social', '#FFFC00', 'dark', 'star', 7, false),
  ('twitch', 'Twitch', 'social', '#9146FF', 'light', 'play', 8, false),
  ('discord', 'Discord', 'social', '#5865F2', 'light', 'mic', 9, false),
  ('social-soundcloud', 'SoundCloud', 'social', '#FF5500', 'light', 'cloud', 10, false),
  ('social-bandcamp', 'Bandcamp', 'social', '#1DA0C3', 'light', 'cassette', 11, false),
  ('website', 'Website', 'social', '#3C4046', 'light', 'hex', 12, false),
  ('whatsapp', 'WhatsApp', 'social', '#25D366', 'dark', 'pulse', 13, false),
  ('telegram', 'Telegram', 'social', '#229ED9', 'light', 'bolt', 14, false),
  ('linkedin', 'LinkedIn', 'social', '#0A66C2', 'light', 'diamond', 15, false),
  ('pinterest', 'Pinterest', 'social', '#E60023', 'light', 'heart', 16, false)
on conflict (id) do nothing;
